#!/usr/bin/env ruby

require_relative 'lib/month'

if ARGV.length != 2
  puts "usage: cal [month] year"
  exit
end

month = ARGV[0].to_i
year = ARGV[1].to_i

unless (1..12).include? month
  puts "cal: #{month} is not a month number (1..12)"
  exit
end

unless (1800..3000).include? year
  puts "cal: year #{year} not in range 1800..3000"
  exit
end

month = Month.new(month, year)
puts month.to_s
