#!/usr/bin/env ruby

require_relative 'lib/month'
require_relative 'lib/year'

unless ARGV.length.between?(1, 2)
  puts "usage: cal [month] year"
  exit
end

begin
  year = ARGV.pop.to_i
  if ARGV.empty?
    year = Year.new(year)
    puts year.to_s
  else
    month = ARGV.pop.to_i
    month = Month.new(month, year)
    puts month.to_s
  end
rescue ArgumentError => e
  puts e.message
end
