#!/usr/bin/env ruby

require_relative 'lib/month'

unless ARGV.length.between?(1, 2)
  puts "usage: cal [month] year"
  exit
end

year = ARGV.pop.to_i
unless (1800..3000).include? year
  puts "cal: year #{year} not in range 1800..3000"
  exit
end

month = ARGV.pop.to_i
unless (1..12).include? month
  puts "cal: #{month} is not a month number (1..12)"
  exit
end


month = Month.new(month, year)
puts month.to_s
